version: "3"

services:
  api:
    image: lisaxabokhai/backendhngtask:latest
    build:
      context: ./api
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: python manage.py runserver 0.0.0.0:8000
    restart: always

  frontend:
    image: lisaxabokhai/frontendhngtask:latest
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    # command: npm run build



